#! /usr/bin/env zsh

yabai -m config layout bsp
yabai -m config split_type auto
yabai -m config auto_balance off
yabai -m config window_border_blur off
yabai -m config window_border off
yabai -m config top_padding 0
yabai -m config bottom_padding 0
yabai -m config right_padding 0
yabai -m config left_padding 0
yabai -m config window_gap 4
yabai -m config mouse_follows_focus on
yabai -m config window_placement second_child
yabai -m config mouse_modifier fn

# exclude Chrome Picture in Picture windows
yabai -m rule --add title="^(Picture in Picture|Picture-in-Picture)$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^FaceTime$" manage=off
yabai -m rule --add app="^Photo Booth$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add title='^Slack \| mini panel$' manage=off layer=above
yabai -m rule --add subrole="^AXSystemDialog$" manage=off mouse_follows_focus=off

# make JetBrains products popup windows float
apps='^(GoLand|DataGrip)$'
yabai -m rule --add app="${apps}" manage=off
yabai -m rule --add app="${apps}" title="( – )" manage=on
yabai -m rule --add app="${apps}" title=".*\[(.*)\].*" manage=on
