vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
vim.g.mapleader = vim.api.nvim_replace_termcodes("<space>", true, true, true)

vim.o.shiftwidth = 4
vim.o.scrolloff = 10
vim.o.relativenumber = true
vim.o.number = true
vim.o.tabstop = 4
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.hidden = true
vim.o.hlsearch = false
vim.o.signcolumn = "yes"
vim.o.swapfile = false
vim.o.undofile = true
vim.o.updatetime = 700
vim.o.mouse = "n"
vim.o.completeopt = "menu,menuone,noselect"
vim.o.timeoutlen = 200
vim.o.clipboard = "unnamedplus"
